server:
  port: 8081
spring:
  application:
    name: photo-manager
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/?authSource=${MONGODB_DB}&replicaSet=${MONGODB_RS}
      database: ${MONGODB_DB}
      auto-index-creation: true
logging:
  level:
    org.springframework.security: DEBUG
